Repository ament/ament_cmake, pull requests merged in 2018-07, with the labels that each got.

#143 Add SKIP_TEST flag to ament_add_gmock()
  ament_cmake_gmock/cmake/ament_add_gmock.cmake
Labels: in review

#144 add signature parameter to docblock
  ament_cmake_core/cmake/symlink_install/install.cmake
Labels: documentation, in review

#145 fix using uninitialized CMake variables
  ament_cmake_core/cmake/core/ament_package.cmake
  ament_cmake_core/cmake/environment_hooks/ament_generate_package_environment.cmake
Labels: in review

#146 fix wrong FOUND flag on repeated inclusion
  ament_cmake_core/cmake/core/templates/nameConfig.cmake.in
Labels: bug, in review

#147 Fast-forward bouncy to catch up with master for patch 1 release
  ament_cmake/package.xml
  ament_cmake_auto/package.xml
  ament_cmake_core/cmake/core/ament_package.cmake
  ament_cmake_core/cmake/core/templates/nameConfig.cmake.in
  ament_cmake_core/cmake/environment_hooks/ament_generate_package_environment.cmake
  ament_cmake_core/cmake/symlink_install/install.cmake
  ament_cmake_core/package.xml
  ament_cmake_export_definitions/package.xml
  ament_cmake_export_dependencies/package.xml
  ament_cmake_export_include_directories/package.xml
  ament_cmake_export_interfaces/package.xml
  ament_cmake_export_libraries/package.xml
  ament_cmake_export_link_flags/package.xml
  ament_cmake_gmock/cmake/ament_add_gmock.cmake
  ament_cmake_gmock/package.xml
  ament_cmake_gtest/package.xml
  ament_cmake_include_directories/package.xml
  ament_cmake_libraries/package.xml
  ament_cmake_nose/package.xml
  ament_cmake_pytest/package.xml
  ament_cmake_python/package.xml
  ament_cmake_target_dependencies/package.xml
  ament_cmake_test/package.xml
Labels: in review
