Repository ament/ament_cmake, pull requests merged in 2019-08, with the labels that each got.

#188 Rename uninstall target so it is unique per project
  ament_cmake_core/ament_cmake_uninstall_target-extras.cmake
Labels: enhancement

#187 generate .dsv files beside known environment hooks
  ament_cmake_core/ament_cmake_environment_hooks-extras.cmake
  ament_cmake_core/cmake/environment_hooks/ament_environment_hooks.cmake
  ament_cmake_core/cmake/environment_hooks/ament_generate_package_environment.cmake
Labels: enhancement, in review

#190 ensure that PYTHON_INSTALL_DIR is initialized for generated .dsv file
  ament_cmake_core/ament_cmake_environment_hooks-extras.cmake
  ament_cmake_python/ament_cmake_python-extras.cmake
Labels: bug, in review

#194 pass unparsed argument of ament_auto_package() to ament_package()
  ament_cmake_auto/cmake/ament_auto_package.cmake
Labels: enhancement, in review

#195 Check existance of uninstall target before creating it
  ament_cmake_core/ament_cmake_uninstall_target-extras.cmake
Labels: enhancement
