Repository ament/ament_cmake, pull requests merged in 2019-11, with the labels that each got.

#209 [backport dashing] pass unparsed argument of ament_auto_package() to ament_package()
  ament_cmake_auto/cmake/ament_auto_package.cmake
Labels: in review

#210 add .dsv env hooks to the local_setup.dsv
  ament_cmake_core/cmake/environment_hooks/ament_generate_package_environment.cmake
Labels: bug, in review

#207 Use regex for more clear string manipulation.
  ament_cmake_core/cmake/environment_hooks/ament_environment_hooks.cmake
Labels: enhancement

#211 [backport eloquent] add .dsv env hooks to the local_setup.dsv
  ament_cmake_core/cmake/environment_hooks/ament_generate_package_environment.cmake
Labels: bug, in review
