Repository ament/ament_cmake, pull requests merged in 2020-04, with the labels that each got.

#226 Enable coverage information generation for pytest tests with CMake
  ament_cmake_pytest/ament_cmake_pytest-extras.cmake
  ament_cmake_pytest/cmake/ament_add_pytest_test.cmake
  ament_cmake_pytest/cmake/ament_get_pytest_cov_version.cmake
Labels: enhancement

#235 use modern interface targets if available, otherwise classic variables
  ament_cmake_target_dependencies/cmake/ament_target_dependencies.cmake
Labels: enhancement

#239 use OUTPUT_NAME of exported library if set
  ament_cmake_export_libraries/cmake/ament_export_libraries.cmake
Labels: bug

#240 add CMake function ament_add_test_label()
  ament_cmake_test/ament_cmake_test-extras.cmake
  ament_cmake_test/cmake/ament_add_test_label.cmake
Labels: enhancement

#242 Drop duplicated <skipped/> element in result file
  ament_cmake_test/ament_cmake_test/__init__.py
Labels: bug, in review

#243 Report skipped tests in CTest output
  ament_cmake_test/cmake/ament_add_test.cmake
Labels: enhancement, in review

#250 Revert "use _TARGETS over deprecated _INTERFACES over classic CMake variables"
  ament_cmake_target_dependencies/cmake/ament_target_dependencies.cmake
Labels: bug

#252 fix order of including exported targets
  ament_cmake_export_targets/cmake/ament_cmake_export_targets-extras.cmake.in
Labels: bug

#254 Fix parallel testing
  ament_cmake_test/ament_cmake_test/__init__.py
Labels: bug
